### ISSUE TITLE
Tree leaves animation if shader tweening of vertices

### ISSUE THREAD

**Issue by kikonen** [kikonen/learnopengl#32]

**Comment by kikonen** [comment]
**DONE**
- added simple USE_TREE_WIND semi-generic mod based logic

**USAGE**
```yaml
    mesh:
      material_modifier:
        shared_definitions:
          USE_TREE_WIND: 1
```
